import type {
  Account,
  Category,
  Merchant,
  Transaction,
  Subscription,
  IncomeEntry,
  Goal,
  GoalAllocation,
  GoalSpendLink,
  WealthAccount,
  EmergencyFund,
  EmergencyFundActivity,
  EmergencyWithdrawalReason,
  YieldProfile,
  YieldRateHistory,
  AssetHolding,
  InvestmentActivity,
  InternalTransfer,
} from "@/lib/types";
import type { TableDescriptor, RemoteRow } from "./types";

function dateOrNull(val: unknown): Date | null {
  if (!val) return null;
  return new Date(val as string);
}

function toISOOrNull(d: Date | null | undefined): string | null {
  return d ? d.toISOString() : null;
}

function toDateStr(d: Date): string {
  return d.toISOString().split("T")[0];
}

const accountDescriptor: TableDescriptor<Account> = {
  name: "accounts",
  localTable: "accounts",
  remoteTable: "accounts",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    type: row.type,
    currency: row.currency,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Account => ({
    id: row.id as string,
    name: row.name as string,
    type: row.type as "main" | "external",
    currency: row.currency as string,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const categoryDescriptor: TableDescriptor<Category> = {
  name: "categories",
  localTable: "categories",
  remoteTable: "categories",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    icon: row.icon,
    color_token: row.colorToken,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Category => ({
    id: row.id as string,
    name: row.name as string,
    icon: row.icon as string,
    colorToken: row.color_token as string,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const merchantDescriptor: TableDescriptor<Merchant> = {
  name: "merchants",
  localTable: "merchants",
  remoteTable: "merchants",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Merchant => ({
    id: row.id as string,
    name: row.name as string,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const transactionDescriptor: TableDescriptor<Transaction> = {
  name: "transactions",
  localTable: "transactions",
  remoteTable: "transactions",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    date: toDateStr(row.date),
    amount: row.amount,
    type: row.type,
    category_id: row.categoryId ?? null,
    merchant_id: row.merchantId ?? null,
    account_id: row.accountId,
    note: row.note ?? null,
    tags: row.tags,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Transaction => ({
    id: row.id as string,
    date: new Date(row.date as string),
    amount: Number(row.amount),
    type: row.type as "expense" | "income",
    categoryId: (row.category_id as string) || undefined,
    merchantId: (row.merchant_id as string) || undefined,
    accountId: row.account_id as string,
    note: (row.note as string) || undefined,
    tags: (row.tags as string[]) || [],
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const subscriptionDescriptor: TableDescriptor<Subscription> = {
  name: "subscriptions",
  localTable: "subscriptions",
  remoteTable: "subscriptions",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    amount: row.amount,
    cadence: row.cadence,
    next_renewal_date: toDateStr(row.nextRenewalDate),
    account_id: row.accountId,
    category_id: row.categoryId ?? null,
    merchant_id: row.merchantId ?? null,
    active: row.active,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Subscription => ({
    id: row.id as string,
    name: row.name as string,
    amount: Number(row.amount),
    cadence: row.cadence as "weekly" | "monthly" | "yearly",
    nextRenewalDate: new Date(row.next_renewal_date as string),
    accountId: row.account_id as string,
    categoryId: (row.category_id as string) || undefined,
    merchantId: (row.merchant_id as string) || undefined,
    active: row.active as boolean,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const incomeEntryDescriptor: TableDescriptor<IncomeEntry> = {
  name: "incomeEntries",
  localTable: "incomeEntries",
  remoteTable: "income_entries",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    month: row.month,
    source: row.source,
    amount: row.amount,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): IncomeEntry => ({
    id: row.id as string,
    month: row.month as string,
    source: row.source as string,
    amount: Number(row.amount),
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const goalDescriptor: TableDescriptor<Goal> = {
  name: "goals",
  localTable: "goals",
  remoteTable: "goals",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    target_amount: row.targetAmount,
    target_date: row.targetDate ?? null,
    account_id: row.accountId,
    archived: row.archived,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): Goal => ({
    id: row.id as string,
    name: row.name as string,
    targetAmount: Number(row.target_amount),
    targetDate: (row.target_date as string) || undefined,
    accountId: row.account_id as string,
    archived: row.archived as boolean,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const goalAllocationDescriptor: TableDescriptor<GoalAllocation> = {
  name: "goalAllocations",
  localTable: "goalAllocations",
  remoteTable: "goal_allocations",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    goal_id: row.goalId,
    date: row.date,
    amount: row.amount,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): GoalAllocation => ({
    id: row.id as string,
    goalId: row.goal_id as string,
    date: row.date as string,
    amount: Number(row.amount),
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const goalSpendLinkDescriptor: TableDescriptor<GoalSpendLink> = {
  name: "goalSpendLinks",
  localTable: "goalSpendLinks",
  remoteTable: "goal_spend_links",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    goal_id: row.goalId,
    transaction_id: row.transactionId,
    amount_applied: row.amountApplied,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): GoalSpendLink => ({
    id: row.id as string,
    goalId: row.goal_id as string,
    transactionId: row.transaction_id as string,
    amountApplied: Number(row.amount_applied),
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const wealthAccountDescriptor: TableDescriptor<WealthAccount> = {
  name: "wealthAccounts",
  localTable: "wealthAccounts",
  remoteTable: "wealth_accounts",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    type: row.type,
    asset_class: row.assetClass,
    balance: row.balance,
    currency: row.currency,
    institution: row.institution ?? null,
    risk_level: row.riskLevel,
    liquidity: row.liquidity,
    insurance_type: row.insuranceType,
    notes: row.notes ?? null,
    archived: row.archived,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): WealthAccount => ({
    id: row.id as string,
    name: row.name as string,
    type: row.type as "cash" | "brokerage",
    assetClass: row.asset_class as "fiat" | "crypto",
    balance: Number(row.balance),
    currency: row.currency as string,
    institution: (row.institution as string) || undefined,
    riskLevel: row.risk_level as "low" | "medium" | "high",
    liquidity: row.liquidity as "immediate" | "short_term" | "long_term",
    insuranceType: row.insurance_type as "FDIC" | "NCUA" | "SIPC" | "none",
    notes: (row.notes as string) || undefined,
    archived: row.archived as boolean,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const emergencyFundDescriptor: TableDescriptor<EmergencyFund> = {
  name: "emergencyFunds",
  localTable: "emergencyFunds",
  remoteTable: "emergency_funds",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    name: row.name,
    wealth_account_id: row.wealthAccountId,
    monthly_expenses: row.monthlyExpenses,
    target_months: row.targetMonths,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): EmergencyFund => ({
    id: row.id as string,
    name: row.name as string,
    wealthAccountId: row.wealth_account_id as string,
    monthlyExpenses: Number(row.monthly_expenses),
    targetMonths: Number(row.target_months),
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const emergencyFundActivityDescriptor: TableDescriptor<EmergencyFundActivity> = {
  name: "emergencyFundActivities",
  localTable: "emergencyFundActivities",
  remoteTable: "emergency_fund_activities",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    emergency_fund_id: row.emergencyFundId,
    type: row.type,
    amount: row.amount,
    date: row.date,
    reason: row.reason ?? null,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): EmergencyFundActivity => ({
    id: row.id as string,
    emergencyFundId: row.emergency_fund_id as string,
    type: row.type as "contribution" | "withdrawal",
    amount: Number(row.amount),
    date: row.date as string,
    reason: (row.reason as EmergencyWithdrawalReason) || undefined,
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const yieldProfileDescriptor: TableDescriptor<YieldProfile> = {
  name: "yieldProfiles",
  localTable: "yieldProfiles",
  remoteTable: "yield_profiles",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    wealth_account_id: row.wealthAccountId,
    rate_type: row.rateType,
    current_rate: row.currentRate,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): YieldProfile => ({
    id: row.id as string,
    wealthAccountId: row.wealth_account_id as string,
    rateType: row.rate_type as "APY" | "APR",
    currentRate: Number(row.current_rate),
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const yieldRateHistoryDescriptor: TableDescriptor<YieldRateHistory> = {
  name: "yieldRateHistories",
  localTable: "yieldRateHistories",
  remoteTable: "yield_rate_histories",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    yield_profile_id: row.yieldProfileId,
    rate: row.rate,
    effective_date: row.effectiveDate,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): YieldRateHistory => ({
    id: row.id as string,
    yieldProfileId: row.yield_profile_id as string,
    rate: Number(row.rate),
    effectiveDate: row.effective_date as string,
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const assetHoldingDescriptor: TableDescriptor<AssetHolding> = {
  name: "assetHoldings",
  localTable: "assetHoldings",
  remoteTable: "asset_holdings",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    wealth_account_id: row.wealthAccountId,
    asset_type: row.assetType,
    symbol: row.symbol,
    name: row.name ?? null,
    quantity: row.quantity,
    cost_basis_total: row.costBasisTotal,
    current_price_per_unit: row.currentPricePerUnit,
    price_updated_at: toISOOrNull(row.priceUpdatedAt),
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): AssetHolding => ({
    id: row.id as string,
    wealthAccountId: row.wealth_account_id as string,
    assetType: row.asset_type as "etf" | "stock" | "crypto",
    symbol: row.symbol as string,
    name: (row.name as string) || undefined,
    quantity: Number(row.quantity),
    costBasisTotal: Number(row.cost_basis_total),
    currentPricePerUnit: Number(row.current_price_per_unit),
    priceUpdatedAt: dateOrNull(row.price_updated_at),
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const investmentActivityDescriptor: TableDescriptor<InvestmentActivity> = {
  name: "investmentActivities",
  localTable: "investmentActivities",
  remoteTable: "investment_activities",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    wealth_account_id: row.wealthAccountId,
    asset_holding_id: row.assetHoldingId ?? null,
    type: row.type,
    date: row.date,
    quantity: row.quantity ?? null,
    price_per_unit: row.pricePerUnit ?? null,
    amount: row.amount ?? null,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): InvestmentActivity => ({
    id: row.id as string,
    wealthAccountId: row.wealth_account_id as string,
    assetHoldingId: (row.asset_holding_id as string) || undefined,
    type: row.type as "buy" | "sell" | "dividend" | "fee" | "priceUpdate",
    date: row.date as string,
    quantity: row.quantity !== null && row.quantity !== undefined ? Number(row.quantity) : undefined,
    pricePerUnit:
      row.price_per_unit !== null && row.price_per_unit !== undefined
        ? Number(row.price_per_unit)
        : undefined,
    amount: row.amount !== null && row.amount !== undefined ? Number(row.amount) : undefined,
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

const internalTransferDescriptor: TableDescriptor<InternalTransfer> = {
  name: "internalTransfers",
  localTable: "internalTransfers",
  remoteTable: "internal_transfers",
  toRemote: (row, userId) => ({
    id: row.id,
    user_id: userId,
    date: row.date,
    amount: row.amount,
    from_type: row.fromType,
    from_id: row.fromId,
    to_type: row.toType,
    to_id: row.toId,
    note: row.note ?? null,
    created_at: row.createdAt.toISOString(),
    updated_at: row.updatedAt.toISOString(),
    deleted_at: toISOOrNull(row.deletedAt),
  }),
  toLocal: (row: RemoteRow): InternalTransfer => ({
    id: row.id as string,
    date: row.date as string,
    amount: Number(row.amount),
    fromType: row.from_type as "account" | "wealthAccount",
    fromId: row.from_id as string,
    toType: row.to_type as "account" | "wealthAccount",
    toId: row.to_id as string,
    note: (row.note as string) || undefined,
    createdAt: new Date(row.created_at as string),
    updatedAt: new Date(row.updated_at as string),
    deletedAt: dateOrNull(row.deleted_at),
  }),
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ALL_DESCRIPTORS: TableDescriptor<any>[] = [
  accountDescriptor,
  categoryDescriptor,
  merchantDescriptor,
  transactionDescriptor,
  subscriptionDescriptor,
  incomeEntryDescriptor,
  goalDescriptor,
  goalAllocationDescriptor,
  goalSpendLinkDescriptor,
  wealthAccountDescriptor,
  emergencyFundDescriptor,
  emergencyFundActivityDescriptor,
  yieldProfileDescriptor,
  yieldRateHistoryDescriptor,
  assetHoldingDescriptor,
  investmentActivityDescriptor,
  internalTransferDescriptor,
];
