import { wealthAccountRepository } from "@/lib/db/repositories/wealth-account.repository";
import { assetHoldingRepository } from "@/lib/db/repositories/asset-holding.repository";
import { emergencyFundRepository } from "@/lib/db/repositories/emergency-fund.repository";
import { emergencyFundActivityRepository } from "@/lib/db/repositories/emergency-fund-activity.repository";
import { yieldProfileRepository } from "@/lib/db/repositories/yield-profile.repository";
import { yieldRateHistoryRepository } from "@/lib/db/repositories/yield-rate-history.repository";
import { investmentActivityRepository } from "@/lib/db/repositories/investment-activity.repository";
import { internalTransferRepository } from "@/lib/db/repositories/internal-transfer.repository";
import type { EmergencyWithdrawalReason } from "@/lib/types";
import {
  calculateHoldingValue,
  calculateUnrealizedGain,
  calculateHoldingRealizedGainTotal,
} from "./investment-calculations.service";
import { calculateEstimatedApyReturn, calculateEstimatedAprReturn } from "./yield-calculations.service";

// ─── Total wealth (net worth, v1 scope) ────────────────────────────────
// Total Wealth = wealth account cash + investment holding values − liabilities(0, future).
// Budget `Account` balances are intentionally excluded: the core app has no balance
// concept for budget accounts (no field, no derived sum, no UI) — see plan decision D9.

export interface WealthTotals {
  totalWealth: number;
  cashTotal: number;
  holdingsValue: number;
  liabilitiesTotal: number;
}

export async function calculateTotalWealth(): Promise<WealthTotals> {
  const wealthAccounts = await wealthAccountRepository.getActive();
  const cashTotal = wealthAccounts.reduce((s, a) => s + a.balance, 0);

  const brokerageIds = new Set(wealthAccounts.filter((a) => a.type === "brokerage").map((a) => a.id));
  const holdings = (await assetHoldingRepository.getAll()).filter(
    (h) => brokerageIds.has(h.wealthAccountId) && h.quantity > 0
  );
  const holdingsValue = holdings.reduce((s, h) => s + calculateHoldingValue(h), 0);

  const liabilitiesTotal = 0; // future — not implemented yet

  return {
    totalWealth: cashTotal + holdingsValue - liabilitiesTotal,
    cashTotal,
    holdingsValue,
    liabilitiesTotal,
  };
}

/**
 * Principal contributed, distinct from wealth generated by growth. Emergency funds and
 * invested (held) positions have a true audited ledger; plain cash accounts don't (their
 * balance is directly editable, see plan decision D6/D7), so their whole balance is
 * treated as "contribution" — a documented simplification, not a bug.
 */
export async function calculateTotalContributions(): Promise<number> {
  const emergencyFunds = await emergencyFundRepository.getAll();
  const emergencyFundAccountIds = new Set(emergencyFunds.map((f) => f.wealthAccountId));

  let emergencyPrincipal = 0;
  for (const fund of emergencyFunds) {
    const contributions = await emergencyFundActivityRepository.getSumByFundId(fund.id, "contribution");
    const withdrawals = await emergencyFundActivityRepository.getSumByFundId(fund.id, "withdrawal");
    emergencyPrincipal += contributions - withdrawals;
  }

  const wealthAccounts = await wealthAccountRepository.getActive();
  const holdings = (await assetHoldingRepository.getAll()).filter((h) => h.quantity > 0);
  const investedPrincipal = holdings.reduce((s, h) => s + h.costBasisTotal, 0);

  // Uninvested brokerage cash was deposited by the user too — without this, it would
  // count toward Total Wealth but not Total Contributions, showing up as phantom "growth".
  const brokerageCashPrincipal = wealthAccounts
    .filter((a) => a.type === "brokerage")
    .reduce((s, a) => s + a.balance, 0);

  const plainCashPrincipal = wealthAccounts
    .filter((a) => a.type === "cash" && !emergencyFundAccountIds.has(a.id))
    .reduce((s, a) => s + a.balance, 0);

  return emergencyPrincipal + investedPrincipal + brokerageCashPrincipal + plainCashPrincipal;
}

export async function calculateTotalGrowth(): Promise<number> {
  const { totalWealth } = await calculateTotalWealth();
  const contributions = await calculateTotalContributions();
  return totalWealth - contributions;
}

/** Projection, not a ledger reconciliation — see plan decision D7. */
export async function calculateYieldEarned(): Promise<number> {
  const profiles = await yieldProfileRepository.getAll();
  let total = 0;
  for (const profile of profiles) {
    const account = await wealthAccountRepository.getById(profile.wealthAccountId);
    if (!account || account.archived) continue;
    total +=
      profile.rateType === "APY"
        ? calculateEstimatedApyReturn(account.balance, profile.currentRate, "annual")
        : calculateEstimatedAprReturn(account.balance, profile.currentRate, "annual");
  }
  return total;
}

async function calculateGrowthThisYear(): Promise<number> {
  const yearStart = `${new Date().getFullYear()}-01-01`;
  const holdings = await assetHoldingRepository.getAll();

  let ytdRealized = 0;
  for (const holding of holdings) {
    const activities = await investmentActivityRepository.getByHoldingId(holding.id);
    ytdRealized += calculateHoldingRealizedGainTotal(activities, yearStart);
  }

  const allInvestmentActivities = await investmentActivityRepository.getAll();
  const ytdDividends = allInvestmentActivities
    .filter((a) => a.type === "dividend" && a.date >= yearStart)
    .reduce((s, a) => s + (a.amount ?? 0), 0);
  const ytdFees = allInvestmentActivities
    .filter((a) => a.type === "fee" && a.date >= yearStart)
    .reduce((s, a) => s + (a.amount ?? 0), 0);

  const activeHoldings = holdings.filter((h) => h.quantity > 0);
  const unrealizedGain = activeHoldings.reduce((s, h) => s + calculateUnrealizedGain(h).amount, 0);

  // Current unrealized gain is a snapshot, not "gained since Jan 1" — a documented
  // approximation given there's no daily net-worth history stored (see known limitations).
  return unrealizedGain + ytdRealized + ytdDividends - ytdFees;
}

// ─── Wealth over time (approximate) ──────────────────────────────────────
// No historical net-worth snapshots are stored, so past points are reconstructed
// by reversing wealth-changing cash flows (contributions/withdrawals, dividends/fees,
// and transfers that crossed the budget<->wealth boundary) off of today's true total.
// Buy/sell activity is cash-neutral for this reconstruction (it just moves cash into a
// holding), so historical market appreciation isn't reflected at past points — a
// documented limitation consistent with the module's "estimated" framing elsewhere.

export interface WealthGrowthPoint {
  month: string; // YYYY-MM
  label: string;
  totalWealth: number;
}

function transferWealthDelta(fromType: string, toType: string, amount: number): number {
  const fromIsWealth = fromType === "wealthAccount";
  const toIsWealth = toType === "wealthAccount";
  if (fromIsWealth === toIsWealth) return 0; // both wealth (no net change) or both budget (untracked)
  return toIsWealth ? amount : -amount;
}

export async function getWealthGrowthSeries(monthsBack = 6): Promise<WealthGrowthPoint[]> {
  const { totalWealth: currentTotal } = await calculateTotalWealth();

  const [emergencyActivities, investmentActivities, transfers] = await Promise.all([
    emergencyFundActivityRepository.getAll(),
    investmentActivityRepository.getAll(),
    internalTransferRepository.getAllSorted(),
  ]);

  const deltas: Array<{ date: string; delta: number }> = [];
  for (const a of emergencyActivities) {
    deltas.push({ date: a.date, delta: a.type === "contribution" ? a.amount : -a.amount });
  }
  for (const a of investmentActivities) {
    if (a.type === "dividend") deltas.push({ date: a.date, delta: a.amount ?? 0 });
    if (a.type === "fee") deltas.push({ date: a.date, delta: -(a.amount ?? 0) });
  }
  for (const t of transfers) {
    const delta = transferWealthDelta(t.fromType, t.toType, t.amount);
    if (delta !== 0) deltas.push({ date: t.date, delta });
  }

  const now = new Date();
  const points: WealthGrowthPoint[] = [];
  for (let i = monthsBack - 1; i >= 0; i--) {
    const cutoff = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const monthEnd = new Date(cutoff.getFullYear(), cutoff.getMonth() + 1, 0);
    const monthEndStr = format2(monthEnd);

    const futureDelta = deltas
      .filter((d) => d.date > monthEndStr)
      .reduce((s, d) => s + d.delta, 0);

    points.push({
      month: `${cutoff.getFullYear()}-${String(cutoff.getMonth() + 1).padStart(2, "0")}`,
      label: cutoff.toLocaleDateString("en-US", { month: "short" }),
      totalWealth: Math.max(0, currentTotal - futureDelta),
    });
  }

  return points;
}

function format2(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// ─── Allocation ─────────────────────────────────────────────────────────

export type WealthAllocationCategory =
  | "Emergency Fund"
  | "Cash Savings"
  | "Yield Products"
  | "ETFs/Stocks"
  | "Crypto"
  | "Other Assets";

export interface AllocationSlice {
  category: WealthAllocationCategory;
  value: number;
  percent: number;
}

export async function calculateWealthAllocation(): Promise<AllocationSlice[]> {
  const accounts = await wealthAccountRepository.getActive();
  const emergencyFunds = await emergencyFundRepository.getAll();
  const emergencyAccountIds = new Set(emergencyFunds.map((f) => f.wealthAccountId));
  const yieldProfiles = await yieldProfileRepository.getAll();
  const yieldAccountIds = new Set(yieldProfiles.map((p) => p.wealthAccountId));
  const holdings = (await assetHoldingRepository.getAll()).filter((h) => h.quantity > 0);

  const buckets: Record<WealthAllocationCategory, number> = {
    "Emergency Fund": 0,
    "Cash Savings": 0,
    "Yield Products": 0,
    "ETFs/Stocks": 0,
    Crypto: 0,
    "Other Assets": 0,
  };

  for (const account of accounts) {
    if (account.type === "brokerage") {
      buckets["Other Assets"] += account.balance;
      continue;
    }
    if (emergencyAccountIds.has(account.id)) {
      buckets["Emergency Fund"] += account.balance;
    } else if (account.assetClass === "crypto") {
      buckets.Crypto += account.balance;
    } else if (yieldAccountIds.has(account.id)) {
      buckets["Yield Products"] += account.balance;
    } else {
      buckets["Cash Savings"] += account.balance;
    }
  }

  for (const holding of holdings) {
    const value = calculateHoldingValue(holding);
    if (holding.assetType === "crypto") {
      buckets.Crypto += value;
    } else {
      buckets["ETFs/Stocks"] += value;
    }
  }

  const total = Object.values(buckets).reduce((s, v) => s + v, 0);
  return (Object.keys(buckets) as WealthAllocationCategory[])
    .map((category) => ({
      category,
      value: buckets[category],
      percent: total > 0 ? (buckets[category] / total) * 100 : 0,
    }))
    .filter((slice) => slice.value > 0);
}

// ─── Overview summary ───────────────────────────────────────────────────

export interface WealthOverviewSummary {
  totalWealth: number;
  emergencyReserves: number;
  savingsAndYield: number;
  investments: number;
  totalContributions: number;
  totalGrowth: number;
  estimatedAnnualYield: number;
  growthThisYear: number;
  allocation: AllocationSlice[];
  accountCount: number;
}

export async function getWealthOverviewSummary(): Promise<WealthOverviewSummary> {
  const accounts = await wealthAccountRepository.getActive();
  const emergencyFunds = await emergencyFundRepository.getAll();
  const emergencyAccountIds = new Set(emergencyFunds.map((f) => f.wealthAccountId));

  const emergencyReserves = accounts
    .filter((a) => emergencyAccountIds.has(a.id))
    .reduce((s, a) => s + a.balance, 0);

  const savingsAndYield = accounts
    .filter((a) => a.type === "cash" && !emergencyAccountIds.has(a.id))
    .reduce((s, a) => s + a.balance, 0);

  const brokerageAccounts = accounts.filter((a) => a.type === "brokerage");
  const brokerageCash = brokerageAccounts.reduce((s, a) => s + a.balance, 0);
  const holdings = (await assetHoldingRepository.getAll()).filter((h) => h.quantity > 0);
  const holdingsValue = holdings.reduce((s, h) => s + calculateHoldingValue(h), 0);
  const investments = brokerageCash + holdingsValue;

  const totals = await calculateTotalWealth();
  const totalContributions = await calculateTotalContributions();
  const totalGrowth = totals.totalWealth - totalContributions;
  const estimatedAnnualYield = await calculateYieldEarned();
  const growthThisYear = await calculateGrowthThisYear();
  const allocation = await calculateWealthAllocation();

  return {
    totalWealth: totals.totalWealth,
    emergencyReserves,
    savingsAndYield,
    investments,
    totalContributions,
    totalGrowth,
    estimatedAnnualYield,
    growthThisYear,
    allocation,
    accountCount: accounts.length,
  };
}

// ─── Unified activity feed ──────────────────────────────────────────────

export type WealthActivityKind =
  | "emergency_contribution"
  | "emergency_withdrawal"
  | "investment_buy"
  | "investment_sell"
  | "investment_dividend"
  | "investment_fee"
  | "investment_price_update"
  | "internal_transfer"
  | "yield_rate_change";

export interface WealthActivityItem {
  id: string;
  kind: WealthActivityKind;
  date: string;
  amount: number;
  label: string;
  detail?: string;
  reason?: EmergencyWithdrawalReason;
  accountId?: string;
  sourceTable:
    | "emergencyFundActivities"
    | "investmentActivities"
    | "internalTransfers"
    | "yieldRateHistories";
}

export interface WealthActivityFilter {
  from?: string; // YYYY-MM-DD
  to?: string;
  wealthAccountId?: string;
  kinds?: WealthActivityKind[];
}

export async function getWealthActivityFeed(
  filter: WealthActivityFilter = {}
): Promise<WealthActivityItem[]> {
  const [emergencyFunds, emergencyActivities, investmentActivities, transfers, yieldProfiles, rateHistories, holdings] =
    await Promise.all([
      emergencyFundRepository.getAll(),
      emergencyFundActivityRepository.getAll(),
      investmentActivityRepository.getAll(),
      internalTransferRepository.getAllSorted(),
      yieldProfileRepository.getAll(),
      yieldRateHistoryRepository.getAll(),
      assetHoldingRepository.getAll(),
    ]);

  const fundById = new Map(emergencyFunds.map((f) => [f.id, f]));
  const holdingById = new Map(holdings.map((h) => [h.id, h]));
  const profileById = new Map(yieldProfiles.map((p) => [p.id, p]));

  const items: WealthActivityItem[] = [];

  for (const a of emergencyActivities) {
    const fund = fundById.get(a.emergencyFundId);
    items.push({
      id: a.id,
      kind: a.type === "contribution" ? "emergency_contribution" : "emergency_withdrawal",
      date: a.date,
      amount: a.amount,
      label:
        a.type === "contribution"
          ? `Contribution to ${fund?.name ?? "Emergency Fund"}`
          : `Withdrawal from ${fund?.name ?? "Emergency Fund"}`,
      detail: a.note,
      reason: a.reason,
      accountId: fund?.wealthAccountId,
      sourceTable: "emergencyFundActivities",
    });
  }

  const investmentLabels: Record<string, string> = {
    buy: "Bought",
    sell: "Sold",
    dividend: "Dividend from",
    fee: "Fee on",
    priceUpdate: "Price update for",
  };
  const investmentKinds: Record<string, WealthActivityKind> = {
    buy: "investment_buy",
    sell: "investment_sell",
    dividend: "investment_dividend",
    fee: "investment_fee",
    priceUpdate: "investment_price_update",
  };

  for (const a of investmentActivities) {
    const holding = a.assetHoldingId ? holdingById.get(a.assetHoldingId) : undefined;
    items.push({
      id: a.id,
      kind: investmentKinds[a.type],
      date: a.date,
      amount: a.amount ?? (a.quantity && a.pricePerUnit ? a.quantity * a.pricePerUnit : 0),
      label: `${investmentLabels[a.type]} ${holding?.symbol ?? "holding"}`,
      detail: a.note,
      accountId: a.wealthAccountId,
      sourceTable: "investmentActivities",
    });
  }

  for (const t of transfers) {
    items.push({
      id: t.id,
      kind: "internal_transfer",
      date: t.date,
      amount: t.amount,
      label: "Internal transfer",
      detail: t.note,
      accountId:
        t.fromType === "wealthAccount" ? t.fromId : t.toType === "wealthAccount" ? t.toId : undefined,
      sourceTable: "internalTransfers",
    });
  }

  for (const r of rateHistories) {
    const profile = profileById.get(r.yieldProfileId);
    items.push({
      id: r.id,
      kind: "yield_rate_change",
      date: r.effectiveDate,
      amount: r.rate,
      label: `Rate changed to ${r.rate}%`,
      detail: r.note,
      accountId: profile?.wealthAccountId,
      sourceTable: "yieldRateHistories",
    });
  }

  let filtered = items;
  if (filter.from) filtered = filtered.filter((i) => i.date >= filter.from!);
  if (filter.to) filtered = filtered.filter((i) => i.date <= filter.to!);
  if (filter.wealthAccountId) filtered = filtered.filter((i) => i.accountId === filter.wealthAccountId);
  if (filter.kinds?.length) filtered = filtered.filter((i) => filter.kinds!.includes(i.kind));

  return filtered.sort((a, b) => b.date.localeCompare(a.date));
}
